### ISSUE TITLE
Can't create a SaaS app with oidc inbound protocol config in a sub org

### ISSUE THREAD

**Issue by dewniMW** [wso2-extensions/identity-organization-management#69]
**Description:**

Create an enterprise login idp in a sub org.

Create a SaaS app as given below. For the user, I have given the org creator of the sub org (user is outside the org). This user has the required permissions to invoke the request in the sub org.

`curl --location --request POST 'https://localhost:9443/o/<sub org id>/api/server/v1/applications' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--header 'Authorization: Basic YWRtaW46YWRtaW4=' \
--data-raw '{
    "name": "B2B SaaS",
    "isManagementApp": true,
    "authenticationSequence": {
        "type": "USER_DEFINED",
        "steps": [
            {
                "id": 1,
                "options": [
                    {
                        "idp": "EnterpriseIDP",
                        "authenticator": "EnterpriseIDPAuthenticator"
                    },
                    {
                        "idp": "LOCAL",
                        "authenticator": "BasicAuthenticator"
                    }
                ]
            }
        ],
        "script": "var onLoginRequest = function(context) {\n   executeStep(1,\n       {\n           authenticationOptions: [{\n               idp: (context.request.params.org && !context.steps[1].idp) ? \"EnterpriseIDP\" : context.steps[1].idp\n           }],\n           authenticatorParams : {\n               common : {\n                   skipIdentifierPreProcess : \"true\"\n               }\n           }\n       },\n       {\n           onSuccess: function (context) {\n               Log.info(\"User successfully completed initial with IDP : \" + context.steps[1].idp);\n               if (context.steps[1].idp === \"EnterpriseIDP\") {\n                   return;\n               }\n           }\n       });\n};\n",
        "subjectStepId": 1,
        "attributeStepId": 1
    },
    "inboundProtocolConfiguration": {
        "oidc": {
            "grantTypes": [
                "authorization_code"
            ],
            "callbackURLs": [
                "http://localhost:8080/pickup-dispatch/oauth2client"
            ]
        }
    }
}'`

Got the following 401 unauthorized error.

`{
    "code": "OAUTH-60003",
    "message": "Invalid Request.",
    "description": "Error while updating OpenIDConnect configuration. No authenticated user found. Failed to register OAuth App.",
    "traceId": "876b48db-7dba-4f59-9dff-4b25ddf9ccda"
}`

The error seems to be due to the validation at https://github.com/wso2-extensions/identity-inbound-auth-oauth/blob/ccc2e5775aba025e9b68970484ba8203b5bef7fd/components/org.wso2.carbon.identity.oauth/src/main/java/org/wso2/carbon/identity/oauth/OAuthAdminServiceImpl.java#L240-L242 where the username is not set due to https://github.com/wso2-extensions/identity-carbon-auth-rest/blob/c49eed43fa4ef833b68a4d24979dda22d2fdfb79/components/org.wso2.carbon.identity.auth.service/src/main/java/org/wso2/carbon/identity/auth/service/handler/AuthenticationHandler.java#L102-L109

**Comment by vinumaddumage** [comment]
fixed with https://github.com/wso2/carbon-identity-framework/pull/4117
